'use client';
import { useMemo, useState } from 'react';
import { jsPDF } from 'jspdf';
import { languages, tr } from '@/lib/i18n';
import type { InnovationPlan, Language } from '@/lib/types';

const L:Record<Language,{desc:string;sequence:string;objective:string;output:string;empty:string}>={
 en:{desc:'Brief description',sequence:'Practical sequence',objective:'Objective',output:'Output',empty:'Your tailored dynamic will appear here.'},es:{desc:'Descripción breve',sequence:'Secuencia práctica',objective:'Objetivo',output:'Entregable',empty:'Tu dinámica personalizada aparecerá aquí.'},fr:{desc:'Description brève',sequence:'Séquence pratique',objective:'Objectif',output:'Livrable',empty:'Votre dynamique personnalisée apparaîtra ici.'},zh:{desc:'简要说明',sequence:'实践流程',objective:'目标',output:'产出',empty:'您的定制创新活动将显示在这里。'},ja:{desc:'概要',sequence:'実践シーケンス',objective:'目標',output:'成果物',empty:'カスタマイズされたダイナミクスがここに表示されます。'},ru:{desc:'Краткое описание',sequence:'Практическая последовательность',objective:'Цель',output:'Результат',empty:'Ваша персональная динамика появится здесь.'},ko:{desc:'간단한 설명',sequence:'실전 순서',objective:'목표',output:'산출물',empty:'맞춤형 혁신 활동이 여기에 표시됩니다.'},de:{desc:'Kurzbeschreibung',sequence:'Praktische Sequenz',objective:'Ziel',output:'Ergebnis',empty:'Ihre individuelle Dynamik erscheint hier.'},ar:{desc:'وصف موجز',sequence:'التسلسل العملي',objective:'الهدف',output:'المخرج',empty:'ستظهر ديناميكية الابتكار المخصصة هنا.'},he:{desc:'תיאור קצר',sequence:'רצף מעשי',objective:'מטרה',output:'תוצר',empty:'דינמיקת החדשנות המותאמת תופיע כאן.'}};
export default function Home(){
 const [lang,setLang]=useState<Language>('es');const ui=useMemo(()=>tr(lang),[lang]);const labels=L[lang];
 const [objective,setObjective]=useState('');const [organization,setOrganization]=useState('');const [audience,setAudience]=useState('');const [participants,setParticipants]=useState(8);const [minutes,setMinutes]=useState(90);const [maturity,setMaturity]=useState('');const [constraints,setConstraints]=useState('');const [plan,setPlan]=useState<InnovationPlan|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const rtl=['ar','he'].includes(lang);
 async function generate(){if(!objective.trim())return;setLoading(true);setError('');setPlan(null);try{const r=await fetch('/api/generate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({language:lang,objective,organization,audience,durationMinutes:minutes,participants,maturity,constraints})});if(!r.ok)throw new Error(await r.text());setPlan(await r.json());}catch(e:any){setError(e.message||'Error');}finally{setLoading(false)}}
 function pdf(){if(!plan)return;const d=new jsPDF({unit:'pt',format:'a4'});const margin=48;let y=52;d.setFont('helvetica','bold');d.setFontSize(10);d.text('INNOVACTION IN ACTION',margin,y);y+=25;d.setFontSize(22);d.text(plan.title,margin,y);y+=28;d.setFont('helvetica','normal');d.setFontSize(10);d.text('Alberto Muñoz · From ideas to real impact',margin,y);y+=28;const add=(title:string,lines:string[])=>{d.setFont('helvetica','bold');d.setFontSize(13);d.text(title,margin,y);y+=18;d.setFont('helvetica','normal');d.setFontSize(10);for(const line of lines){const arr=d.splitTextToSize(line,500);if(y+arr.length*14>790){d.addPage();y=52;}d.text(arr,margin,y);y+=arr.length*14+6;}y+=8};add(labels.objective,[plan.objective]);add(labels.desc,[plan.rationale]);plan.activities.forEach((a,i)=>add(`${i+1}. ${a.title} · ${a.minutes} min`,[a.purpose,...a.instructions,`${labels.output}: ${a.output}`]));d.save('innovaction-in-action.pdf')}
 return <main dir={rtl?'rtl':'ltr'}><nav><div className="brand"><img src="/innovaction-logo.webp" alt="Mexican spinning top Innovaction logo"/><div><span>Innovaction in Action</span><small>From ideas to real impact</small></div></div><select value={lang} onChange={e=>{setLang(e.target.value as Language);setPlan(null)}}>{languages.map(l=><option key={l.code} value={l.code}>{l.label}</option>)}</select></nav>
 <section className="hero"><div className="tag">{ui.tag}</div><h1><span>Innovaction</span> in Action</h1><p>{ui.subtitle}</p><div className="bookLabel">🌀 Innovaction knowledge · AI-powered dynamics · Alberto Muñoz</div></section>
 <section className="grid"><div className="card input"><label>{ui.objective}</label><textarea value={objective} onChange={e=>setObjective(e.target.value)} placeholder={ui.placeholder}/><div className="fields"><input value={organization} onChange={e=>setOrganization(e.target.value)} placeholder={ui.organization}/><input value={audience} onChange={e=>setAudience(e.target.value)} placeholder={ui.audience}/><input value={maturity} onChange={e=>setMaturity(e.target.value)} placeholder={ui.maturity}/><input value={constraints} onChange={e=>setConstraints(e.target.value)} placeholder={ui.constraints}/><label>{ui.participants}<input type="number" min="1" max="100" value={participants} onChange={e=>setParticipants(+e.target.value)}/></label><label>{ui.minutes}<input type="number" min="15" max="480" value={minutes} onChange={e=>setMinutes(+e.target.value)}/></label></div><button onClick={generate} disabled={loading||!objective.trim()}>{loading?ui.working:ui.generate}</button>{error&&<p className="error">{error}</p>}</div>
 <div className="card output">{plan?<><div className="resultHead"><div><div className="tag">INNOVACTION IN ACTION · AI + RAG + SPARK</div><h2>{plan.title}</h2></div><button className="ghost" onClick={pdf}>{ui.report}</button></div><section className="summary"><div><b>{labels.objective}</b><p>{plan.objective}</p><b>{labels.desc}</b><p>{plan.rationale}</p></div><img src="/innovaction-logo.webp" alt="Innovaction spinning top"/></section><h3 className="sequenceTitle">{labels.sequence}</h3><div className="sequenceBar">{plan.activities.map((a,i)=><div key={i}><span>{i+1}</span><b>{a.title}</b><small>{a.minutes} min</small></div>)}</div><div className="timeline">{plan.activities.map((a,i)=><article key={i}><div className="num">{i+1}</div><div><h3>{a.title}<small>{a.minutes} min</small></h3><p>{a.purpose}</p><strong>{labels.output}:</strong> {a.output}</div></article>)}</div></>:<div className="empty"><img src="/innovaction-logo.webp" alt="Innovaction spinning top"/><div className="wordmark"><b>Innovaction</b> in Action</div><h2>Innovation = invention × value</h2><p>{labels.empty}</p></div>}</div></section><footer><b>Innovaction in Action</b> · From ideas to real impact · Alberto Muñoz</footer></main>}
