import { Language } from './types';
export const languages: {code:Language; label:string; dir?:'rtl'}[] = [
  {code:'en',label:'English'}, {code:'es',label:'Español'}, {code:'fr',label:'Français'},
  {code:'zh',label:'中文'}, {code:'ja',label:'日本語'}, {code:'ru',label:'Русский'},
  {code:'ko',label:'한국어'}, {code:'de',label:'Deutsch'}, {code:'ar',label:'العربية',dir:'rtl'},
  {code:'he',label:'עברית',dir:'rtl'}
];
const t:any = {
  en:{tag:'From objective to action',title:'Innovaction in Action',subtitle:'AI-guided innovation dynamics grounded in the Innovaction knowledge base.',objective:'Define your innovation objective',placeholder:'Example: Reduce unplanned downtime in a manufacturing line by 30% using AI without replacing operators.',generate:'Generate innovation dynamic',participants:'Participants',minutes:'Minutes',organization:'Organization / context',audience:'Audience',maturity:'Current maturity / TRL',constraints:'Constraints',report:'Generate PDF',working:'Designing your dynamic…'},
  es:{tag:'Del objetivo a la acción',title:'Innovaction in Action',subtitle:'Dinámicas de innovación guiadas por IA y fundamentadas en la base de conocimiento Innovaction.',objective:'Define tu objetivo de innovación',placeholder:'Ejemplo: Reducir 30% los paros no planeados en una línea de manufactura usando IA sin reemplazar operadores.',generate:'Generar dinámica de innovación',participants:'Participantes',minutes:'Minutos',organization:'Organización / contexto',audience:'Audiencia',maturity:'Madurez actual / TRL',constraints:'Restricciones',report:'Generar PDF',working:'Diseñando tu dinámica…'},
  fr:{tag:"De l’objectif à l’action",title:'Innovaction in Action',subtitle:"Dynamiques d’innovation guidées par l’IA et fondées sur la base Innovaction.",objective:"Définissez votre objectif d’innovation",placeholder:"Exemple : Réduire de 30 % les arrêts non planifiés avec l’IA sans remplacer les opérateurs.",generate:"Générer la dynamique",participants:'Participants',minutes:'Minutes',organization:'Organisation / contexte',audience:'Public',maturity:'Maturité / TRL',constraints:'Contraintes',report:'Générer le PDF',working:'Conception de votre dynamique…'},
  zh:{tag:'从目标到行动',title:'Innovaction in Action',subtitle:'基于 Innovaction 知识库的 AI 创新活动设计。',objective:'定义你的创新目标',placeholder:'示例：在不替代操作员的前提下，利用 AI 将非计划停机减少 30%。',generate:'生成创新活动',participants:'参与人数',minutes:'分钟',organization:'组织 / 场景',audience:'受众',maturity:'当前成熟度 / TRL',constraints:'约束',report:'生成 PDF',working:'正在设计创新活动…'},
  ja:{tag:'目標から実行へ',title:'Innovaction in Action',subtitle:'Innovaction 知識ベースに基づく AI 支援のイノベーション・ダイナミクス。',objective:'イノベーション目標を定義',placeholder:'例：作業者を置き換えずにAIで計画外停止を30%削減する。',generate:'ダイナミクスを生成',participants:'参加者',minutes:'分',organization:'組織 / 文脈',audience:'対象者',maturity:'成熟度 / TRL',constraints:'制約',report:'PDFを生成',working:'ダイナミクスを設計中…'},
  ru:{tag:'От цели к действию',title:'Innovaction in Action',subtitle:'Инновационные практики с ИИ на базе знаний Innovaction.',objective:'Определите цель инновации',placeholder:'Пример: сократить незапланированные простои на 30% с помощью ИИ без замены операторов.',generate:'Создать динамику',participants:'Участники',minutes:'Минуты',organization:'Организация / контекст',audience:'Аудитория',maturity:'Зрелость / TRL',constraints:'Ограничения',report:'Создать PDF',working:'Проектируем динамику…'},
  ko:{tag:'목표에서 실행으로',title:'Innovaction in Action',subtitle:'Innovaction 지식 기반의 AI 혁신 활동 설계.',objective:'혁신 목표를 정의하세요',placeholder:'예: 작업자를 대체하지 않고 AI로 비계획 정지를 30% 줄이기.',generate:'혁신 활동 생성',participants:'참가자',minutes:'분',organization:'조직 / 맥락',audience:'대상',maturity:'성숙도 / TRL',constraints:'제약',report:'PDF 생성',working:'혁신 활동을 설계 중…'},
  de:{tag:'Vom Ziel zur Aktion',title:'Innovaction in Action',subtitle:'KI-gestützte Innovationsdynamiken auf Basis der Innovaction-Wissensbasis.',objective:'Definieren Sie Ihr Innovationsziel',placeholder:'Beispiel: Ungeplante Stillstände mit KI um 30 % senken, ohne Bediener zu ersetzen.',generate:'Innovationsdynamik erzeugen',participants:'Teilnehmende',minutes:'Minuten',organization:'Organisation / Kontext',audience:'Zielgruppe',maturity:'Reifegrad / TRL',constraints:'Einschränkungen',report:'PDF erzeugen',working:'Dynamik wird entworfen…'},
  ar:{tag:'من الهدف إلى التنفيذ',title:'Innovaction in Action',subtitle:'ديناميكيات ابتكار مدعومة بالذكاء الاصطناعي ومبنية على قاعدة معرفة Innovaction.',objective:'عرّف هدف الابتكار',placeholder:'مثال: خفض التوقف غير المخطط بنسبة 30% باستخدام الذكاء الاصطناعي دون استبدال المشغلين.',generate:'إنشاء ديناميكية الابتكار',participants:'المشاركون',minutes:'الدقائق',organization:'المنظمة / السياق',audience:'الجمهور',maturity:'النضج / TRL',constraints:'القيود',report:'إنشاء PDF',working:'جارٍ تصميم الديناميكية…'},
  he:{tag:'מהמטרה לפעולה',title:'Innovaction in Action',subtitle:'דינמיקות חדשנות מונחות AI המבוססות על מאגר הידע Innovaction.',objective:'הגדירו את יעד החדשנות',placeholder:'דוגמה: להפחית ב-30% השבתות לא מתוכננות בעזרת AI מבלי להחליף מפעילים.',generate:'צור דינמיקת חדשנות',participants:'משתתפים',minutes:'דקות',organization:'ארגון / הקשר',audience:'קהל',maturity:'בשלות / TRL',constraints:'מגבלות',report:'צור PDF',working:'מעצב את הדינמיקה…'}
};
export function tr(lang:Language){ return t[lang] || t.en; }
