import { NextRequest, NextResponse } from 'next/server';
import type { InnovationPlan } from '@/lib/types';
function demo(body:any):InnovationPlan{
  const m=Math.max(30,Number(body.durationMinutes||90)); const parts=[Math.round(m*.15),Math.round(m*.2),Math.round(m*.25),Math.round(m*.25)]; parts.push(m-parts.reduce((a,b)=>a+b,0));
  return {title:'Innovaction Sprint',objective:body.objective,rationale:'A practical sequence that moves from problem framing to value, concept validation and an actionable experiment.',activities:[
    {title:'Frame the need',minutes:parts[0],purpose:'Separate the underlying need from the first solution idea.',instructions:['Write the problem as an observable situation.','Identify users, stakeholders and the value at stake.','List constraints and uncertainties.'],output:'Shared problem statement',sourceTags:['problem framing','strategy']},
    {title:'Innovation Game: recombine',minutes:parts[1],purpose:'Generate alternatives by recombining methods, places, practices and technologies.',instructions:['Create four card piles: methods, technologies, users/places and constraints.','Draw one from each pile and force three unexpected combinations.','Keep the two combinations with the clearest value hypothesis.'],output:'2-3 innovation concepts',sourceTags:['Innovation Games']},
    {title:'Value + Customer Journey',minutes:parts[2],purpose:'Test whether the concept solves something people need and can adopt.',instructions:['Map decision, experience and remembered utility.','Write pains, gains and evidence needed.','Define one measurable value hypothesis.'],output:'Value hypothesis and journey',sourceTags:['Canvas','Customer Journey']},
    {title:'TRL / POC / MVP decision',minutes:parts[3],purpose:'Match the next experiment to technological maturity.',instructions:['Estimate current TRL.','Define what must be proven technically (POC).','Define what must be proven with users/market (MVP).','Identify IP/patent and freedom-to-operate questions.'],output:'Next validation experiment',sourceTags:['TRL','POC','MVP','IP']},
    {title:'Action contract',minutes:parts[4],purpose:'Convert the session into execution.',instructions:['Assign an owner and deadline.','Choose 3 metrics that matter.','Define stop / pivot / continue criteria.'],output:'30-day action plan',sourceTags:['metrics','execution']}
  ],materials:['Sticky notes or collaborative board','Timer','Access to relevant evidence/data','Prototype tools as needed'],metrics:['Evidence collected from target users','Technical uncertainty reduced','Value hypothesis validated or rejected','Clear next TRL transition'],risks:['Falling in love with the first solution','Confusing POC with MVP','Skipping IP / freedom-to-operate review','Optimizing activity instead of value'],nextSteps:['Run the first experiment within 7 days','Capture evidence and update the innovation canvas','Reassess TRL and decide: continue, pivot or stop'],references:['Innovaction - Innovation Games','Innovaction - Design Thinking and Canvas','Innovaction - TRL / POC / MVP','Innovaction - Technology surveillance and IP']};
}
export async function POST(req:NextRequest){ const body=await req.json(); const base=process.env.SPARK_INNOVACTION_API_URL; if(!base) return NextResponse.json(demo(body)); try{const r=await fetch(`${base.replace(/\/$/,'')}/generate`,{method:'POST',headers:{'content-type':'application/json','x-api-key':process.env.SPARK_INNOVACTION_API_KEY||''},body:JSON.stringify(body),cache:'no-store'}); if(!r.ok) throw new Error(`Spark ${r.status}`); return NextResponse.json(await r.json());}catch(e){return NextResponse.json(demo(body));} }
